apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
  namespace: gravensteiner
spec:
  params:
    - default: k8s
      description: The directory in source that contains yaml manifests
      name: manifest_dir
      type: string
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - args:
        - '-c'
        - oc apply -f $(inputs.params.manifest_dir)
      command:
        - /bin/bash
      image: quay.io/openshift/origin-cli
      name: apply
      resources: {}
      workingDir: /workspace/source
