apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
  namespace: gravensteiner
spec:
  resources:
    inputs:
      - {type: image, name: image}
  params:
    - name: deployment
      description: The name of the deployment path the image
      type: string
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli
      command:
        - /bin/bash
      args:
        - '-c'
        - >-
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
            "containers": [{
              "name": "$(inputs.params.deployment)",
              "image": "$(inputs.resources.image.url)"
            }]
          }}}}'